#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 130
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 66
#define ALIAS_COUNT 0
#define TOKEN_COUNT 45
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 14
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_ident = 1,
  sym_package_header = 2,
  anon_sym_func = 3,
  anon_sym_LPAREN = 4,
  anon_sym_COMMA = 5,
  anon_sym_RPAREN = 6,
  anon_sym_DASH_GT = 7,
  anon_sym_LBRACE = 8,
  anon_sym_SEMI = 9,
  anon_sym_RBRACE = 10,
  anon_sym_record = 11,
  anon_sym_resource = 12,
  anon_sym_COLON = 13,
  anon_sym_let = 14,
  anon_sym_var = 15,
  anon_sym_EQ = 16,
  anon_sym_return = 17,
  anon_sym_throw = 18,
  anon_sym_break = 19,
  anon_sym_continue = 20,
  anon_sym_PLUS_EQ = 21,
  anon_sym_DASH_EQ = 22,
  anon_sym_STAR_EQ = 23,
  anon_sym_SLASH_EQ = 24,
  anon_sym_QMARK_EQ = 25,
  anon_sym_PLUS = 26,
  anon_sym_DASH = 27,
  anon_sym_STAR = 28,
  anon_sym_SLASH = 29,
  anon_sym_QMARK = 30,
  anon_sym_AMP_AMP = 31,
  anon_sym_PIPE_PIPE = 32,
  anon_sym_AMP = 33,
  anon_sym_PIPE = 34,
  anon_sym_EQ_EQ = 35,
  anon_sym_BANG_EQ = 36,
  anon_sym_LT_EQ = 37,
  anon_sym_GT_EQ = 38,
  anon_sym_LT = 39,
  anon_sym_GT = 40,
  anon_sym_in = 41,
  anon_sym_LF = 42,
  anon_sym_CR = 43,
  sym_comment = 44,
  sym_source_file = 45,
  sym_toplevel = 46,
  sym_func = 47,
  sym_record = 48,
  sym_resource = 49,
  sym_field = 50,
  sym_statement = 51,
  sym_declaration = 52,
  sym_assignment = 53,
  sym_control = 54,
  sym_expression = 55,
  sym_type = 56,
  sym_assignment_operator = 57,
  sym_binary_operator = 58,
  sym_newline = 59,
  aux_sym_source_file_repeat1 = 60,
  aux_sym_func_repeat1 = 61,
  aux_sym_func_repeat2 = 62,
  aux_sym_record_repeat1 = 63,
  aux_sym_resource_repeat1 = 64,
  aux_sym_resource_repeat2 = 65,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_ident] = "ident",
  [sym_package_header] = "package_header",
  [anon_sym_func] = "func",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LBRACE] = "{",
  [anon_sym_SEMI] = ";",
  [anon_sym_RBRACE] = "}",
  [anon_sym_record] = "record",
  [anon_sym_resource] = "resource",
  [anon_sym_COLON] = ":",
  [anon_sym_let] = "let",
  [anon_sym_var] = "var",
  [anon_sym_EQ] = "=",
  [anon_sym_return] = "return",
  [anon_sym_throw] = "throw",
  [anon_sym_break] = "break",
  [anon_sym_continue] = "continue",
  [anon_sym_PLUS_EQ] = "+=",
  [anon_sym_DASH_EQ] = "-=",
  [anon_sym_STAR_EQ] = "*=",
  [anon_sym_SLASH_EQ] = "/=",
  [anon_sym_QMARK_EQ] = "\?=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_QMARK] = "\?",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_AMP] = "&",
  [anon_sym_PIPE] = "|",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_in] = "in",
  [anon_sym_LF] = "\n",
  [anon_sym_CR] = "\r",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_toplevel] = "toplevel",
  [sym_func] = "func",
  [sym_record] = "record",
  [sym_resource] = "resource",
  [sym_field] = "field",
  [sym_statement] = "statement",
  [sym_declaration] = "declaration",
  [sym_assignment] = "assignment",
  [sym_control] = "control",
  [sym_expression] = "expression",
  [sym_type] = "type",
  [sym_assignment_operator] = "assignment_operator",
  [sym_binary_operator] = "binary_operator",
  [sym_newline] = "newline",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_func_repeat1] = "func_repeat1",
  [aux_sym_func_repeat2] = "func_repeat2",
  [aux_sym_record_repeat1] = "record_repeat1",
  [aux_sym_resource_repeat1] = "resource_repeat1",
  [aux_sym_resource_repeat2] = "resource_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_ident] = sym_ident,
  [sym_package_header] = sym_package_header,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_record] = anon_sym_record,
  [anon_sym_resource] = anon_sym_resource,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_throw] = anon_sym_throw,
  [anon_sym_break] = anon_sym_break,
  [anon_sym_continue] = anon_sym_continue,
  [anon_sym_PLUS_EQ] = anon_sym_PLUS_EQ,
  [anon_sym_DASH_EQ] = anon_sym_DASH_EQ,
  [anon_sym_STAR_EQ] = anon_sym_STAR_EQ,
  [anon_sym_SLASH_EQ] = anon_sym_SLASH_EQ,
  [anon_sym_QMARK_EQ] = anon_sym_QMARK_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_CR] = anon_sym_CR,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_toplevel] = sym_toplevel,
  [sym_func] = sym_func,
  [sym_record] = sym_record,
  [sym_resource] = sym_resource,
  [sym_field] = sym_field,
  [sym_statement] = sym_statement,
  [sym_declaration] = sym_declaration,
  [sym_assignment] = sym_assignment,
  [sym_control] = sym_control,
  [sym_expression] = sym_expression,
  [sym_type] = sym_type,
  [sym_assignment_operator] = sym_assignment_operator,
  [sym_binary_operator] = sym_binary_operator,
  [sym_newline] = sym_newline,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_func_repeat1] = aux_sym_func_repeat1,
  [aux_sym_func_repeat2] = aux_sym_func_repeat2,
  [aux_sym_record_repeat1] = aux_sym_record_repeat1,
  [aux_sym_resource_repeat1] = aux_sym_resource_repeat1,
  [aux_sym_resource_repeat2] = aux_sym_resource_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_package_header] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_record] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_resource] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_throw] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_break] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_continue] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CR] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_toplevel] = {
    .visible = true,
    .named = true,
  },
  [sym_func] = {
    .visible = true,
    .named = true,
  },
  [sym_record] = {
    .visible = true,
    .named = true,
  },
  [sym_resource] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_control] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_func_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_func_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_record_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_resource_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_resource_repeat2] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 32,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 54,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 105,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 118,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      ADVANCE_MAP(
        '!', 4,
        '&', 38,
        '(', 16,
        ')', 18,
        '*', 33,
        '+', 30,
        ',', 17,
        '-', 32,
        '/', 34,
        ':', 23,
        ';', 21,
        '<', 44,
        '=', 24,
        '>', 45,
        '?', 35,
        't', 48,
        '{', 20,
        '|', 39,
        '}', 22,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 51,
        '\r', 52,
        '!', 4,
        '&', 38,
        '*', 33,
        '+', 30,
        ',', 17,
        '-', 31,
        '/', 34,
        ':', 23,
        ';', 21,
        '<', 44,
        '=', 24,
        '>', 45,
        '?', 35,
        '|', 39,
        '}', 22,
      );
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(53);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(41);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 10:
      if (lookahead == 'g') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == 'k') ADVANCE(7);
      END_STATE();
    case 12:
      if (lookahead == 'p') ADVANCE(6);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_package_header);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(40);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_PLUS_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DASH_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_STAR_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_SLASH_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_QMARK_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '=') ADVANCE(25);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '=') ADVANCE(26);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '=') ADVANCE(26);
      if (lookahead == '>') ADVANCE(19);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '=') ADVANCE(27);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(53);
      if (lookahead == '=') ADVANCE(28);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_QMARK);
      if (lookahead == '=') ADVANCE(29);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == '&') ADVANCE(36);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '|') ADVANCE(37);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(42);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(43);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == ':') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'd') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'o') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'o') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\r') ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_CR);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\r') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '^') ADVANCE(53);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'b', 1,
        'c', 2,
        'f', 3,
        'i', 4,
        'l', 5,
        'r', 6,
        't', 7,
        'v', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 3:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 7:
      if (lookahead == 'h') ADVANCE(15);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 10:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(21);
      if (lookahead == 's') ADVANCE(22);
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 15:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 16:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(26);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(28);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(29);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 23:
      if (lookahead == 'u') ADVANCE(31);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 26:
      if (lookahead == 'k') ADVANCE(33);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(34);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_func);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(35);
      END_STATE();
    case 30:
      if (lookahead == 'u') ADVANCE(36);
      END_STATE();
    case 31:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 32:
      if (lookahead == 'w') ADVANCE(38);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_break);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(39);
      END_STATE();
    case 35:
      if (lookahead == 'd') ADVANCE(40);
      END_STATE();
    case 36:
      if (lookahead == 'r') ADVANCE(41);
      END_STATE();
    case 37:
      if (lookahead == 'n') ADVANCE(42);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_throw);
      END_STATE();
    case 39:
      if (lookahead == 'u') ADVANCE(43);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_record);
      END_STATE();
    case 41:
      if (lookahead == 'c') ADVANCE(44);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 44:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_continue);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_resource);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 13},
  [11] = {.lex_state = 13},
  [12] = {.lex_state = 13},
  [13] = {.lex_state = 13},
  [14] = {.lex_state = 13},
  [15] = {.lex_state = 13},
  [16] = {.lex_state = 13},
  [17] = {.lex_state = 13},
  [18] = {.lex_state = 13},
  [19] = {.lex_state = 13},
  [20] = {.lex_state = 13},
  [21] = {.lex_state = 13},
  [22] = {.lex_state = 13},
  [23] = {.lex_state = 13},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 13},
  [27] = {.lex_state = 13},
  [28] = {.lex_state = 13},
  [29] = {.lex_state = 13},
  [30] = {.lex_state = 13},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 13},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 13},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 13},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 13},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 13},
  [58] = {.lex_state = 13},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 13},
  [61] = {.lex_state = 13},
  [62] = {.lex_state = 13},
  [63] = {.lex_state = 13},
  [64] = {.lex_state = 13},
  [65] = {.lex_state = 13},
  [66] = {.lex_state = 13},
  [67] = {.lex_state = 13},
  [68] = {.lex_state = 13},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 13},
  [71] = {.lex_state = 13},
  [72] = {.lex_state = 13},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 13},
  [75] = {.lex_state = 13},
  [76] = {.lex_state = 13},
  [77] = {.lex_state = 13},
  [78] = {.lex_state = 13},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 13},
  [81] = {.lex_state = 13},
  [82] = {.lex_state = 13},
  [83] = {.lex_state = 13},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 13},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 13},
  [88] = {.lex_state = 13},
  [89] = {.lex_state = 13},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 13},
  [93] = {.lex_state = 13},
  [94] = {.lex_state = 13},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 13},
  [97] = {.lex_state = 13},
  [98] = {.lex_state = 13},
  [99] = {.lex_state = 13},
  [100] = {.lex_state = 13},
  [101] = {.lex_state = 13},
  [102] = {.lex_state = 13},
  [103] = {.lex_state = 13},
  [104] = {.lex_state = 13},
  [105] = {.lex_state = 13},
  [106] = {.lex_state = 13},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 13},
  [109] = {.lex_state = 13},
  [110] = {.lex_state = 13},
  [111] = {.lex_state = 13},
  [112] = {.lex_state = 13},
  [113] = {.lex_state = 13},
  [114] = {.lex_state = 13},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 13},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 13},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 13},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 13},
  [127] = {.lex_state = 13},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [sym_package_header] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_record] = ACTIONS(1),
    [anon_sym_resource] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_throw] = ACTIONS(1),
    [anon_sym_break] = ACTIONS(1),
    [anon_sym_continue] = ACTIONS(1),
    [anon_sym_PLUS_EQ] = ACTIONS(1),
    [anon_sym_DASH_EQ] = ACTIONS(1),
    [anon_sym_STAR_EQ] = ACTIONS(1),
    [anon_sym_SLASH_EQ] = ACTIONS(1),
    [anon_sym_QMARK_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(125),
    [sym_toplevel] = STATE(28),
    [sym_func] = STATE(80),
    [sym_record] = STATE(80),
    [sym_resource] = STATE(80),
    [aux_sym_source_file_repeat1] = STATE(28),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_package_header] = ACTIONS(7),
    [anon_sym_func] = ACTIONS(9),
    [anon_sym_record] = ACTIONS(11),
    [anon_sym_resource] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(19), 1,
      sym_comment,
    STATE(98), 1,
      sym_assignment_operator,
    ACTIONS(17), 6,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_QMARK_EQ,
    ACTIONS(15), 20,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_in,
      anon_sym_LF,
      anon_sym_CR,
  [37] = 4,
    ACTIONS(19), 1,
      sym_comment,
    STATE(110), 1,
      sym_binary_operator,
    ACTIONS(21), 4,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LF,
      anon_sym_CR,
    ACTIONS(23), 16,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_in,
  [68] = 4,
    ACTIONS(19), 1,
      sym_comment,
    STATE(110), 1,
      sym_binary_operator,
    ACTIONS(25), 4,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LF,
      anon_sym_CR,
    ACTIONS(23), 16,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_in,
  [99] = 4,
    ACTIONS(19), 1,
      sym_comment,
    STATE(110), 1,
      sym_binary_operator,
    ACTIONS(27), 4,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LF,
      anon_sym_CR,
    ACTIONS(23), 16,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_in,
  [130] = 4,
    ACTIONS(19), 1,
      sym_comment,
    STATE(110), 1,
      sym_binary_operator,
    ACTIONS(29), 4,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LF,
      anon_sym_CR,
    ACTIONS(23), 16,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_in,
  [161] = 4,
    ACTIONS(19), 1,
      sym_comment,
    STATE(110), 1,
      sym_binary_operator,
    ACTIONS(31), 4,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LF,
      anon_sym_CR,
    ACTIONS(23), 16,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_in,
  [192] = 3,
    ACTIONS(19), 1,
      sym_comment,
    STATE(110), 1,
      sym_binary_operator,
    ACTIONS(33), 20,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_in,
      anon_sym_LF,
      anon_sym_CR,
  [221] = 2,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(15), 20,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_in,
      anon_sym_LF,
      anon_sym_CR,
  [247] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_ident,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_expression,
    STATE(38), 1,
      sym_statement,
    ACTIONS(39), 2,
      anon_sym_let,
      anon_sym_var,
    STATE(69), 3,
      sym_declaration,
      sym_assignment,
      sym_control,
    ACTIONS(41), 4,
      anon_sym_return,
      anon_sym_throw,
      anon_sym_break,
      anon_sym_continue,
  [278] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_ident,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_expression,
    STATE(43), 1,
      sym_statement,
    ACTIONS(39), 2,
      anon_sym_let,
      anon_sym_var,
    STATE(69), 3,
      sym_declaration,
      sym_assignment,
      sym_control,
    ACTIONS(41), 4,
      anon_sym_return,
      anon_sym_throw,
      anon_sym_break,
      anon_sym_continue,
  [309] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_ident,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_expression,
    STATE(73), 1,
      sym_statement,
    ACTIONS(39), 2,
      anon_sym_let,
      anon_sym_var,
    STATE(69), 3,
      sym_declaration,
      sym_assignment,
      sym_control,
    ACTIONS(41), 4,
      anon_sym_return,
      anon_sym_throw,
      anon_sym_break,
      anon_sym_continue,
  [340] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_ident,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_expression,
    STATE(44), 1,
      sym_statement,
    ACTIONS(39), 2,
      anon_sym_let,
      anon_sym_var,
    STATE(69), 3,
      sym_declaration,
      sym_assignment,
      sym_control,
    ACTIONS(41), 4,
      anon_sym_return,
      anon_sym_throw,
      anon_sym_break,
      anon_sym_continue,
  [371] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_ident,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_expression,
    STATE(51), 1,
      sym_statement,
    ACTIONS(39), 2,
      anon_sym_let,
      anon_sym_var,
    STATE(69), 3,
      sym_declaration,
      sym_assignment,
      sym_control,
    ACTIONS(41), 4,
      anon_sym_return,
      anon_sym_throw,
      anon_sym_break,
      anon_sym_continue,
  [402] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_ident,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_expression,
    STATE(73), 1,
      sym_statement,
    ACTIONS(39), 2,
      anon_sym_let,
      anon_sym_var,
    STATE(69), 3,
      sym_declaration,
      sym_assignment,
      sym_control,
    ACTIONS(41), 4,
      anon_sym_return,
      anon_sym_throw,
      anon_sym_break,
      anon_sym_continue,
  [433] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_ident,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_expression,
    STATE(73), 1,
      sym_statement,
    ACTIONS(39), 2,
      anon_sym_let,
      anon_sym_var,
    STATE(69), 3,
      sym_declaration,
      sym_assignment,
      sym_control,
    ACTIONS(41), 4,
      anon_sym_return,
      anon_sym_throw,
      anon_sym_break,
      anon_sym_continue,
  [464] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_ident,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_expression,
    STATE(73), 1,
      sym_statement,
    ACTIONS(39), 2,
      anon_sym_let,
      anon_sym_var,
    STATE(69), 3,
      sym_declaration,
      sym_assignment,
      sym_control,
    ACTIONS(41), 4,
      anon_sym_return,
      anon_sym_throw,
      anon_sym_break,
      anon_sym_continue,
  [495] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_ident,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_expression,
    STATE(33), 1,
      sym_statement,
    ACTIONS(39), 2,
      anon_sym_let,
      anon_sym_var,
    STATE(69), 3,
      sym_declaration,
      sym_assignment,
      sym_control,
    ACTIONS(41), 4,
      anon_sym_return,
      anon_sym_throw,
      anon_sym_break,
      anon_sym_continue,
  [526] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_ident,
    ACTIONS(53), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_expression,
    STATE(73), 1,
      sym_statement,
    ACTIONS(39), 2,
      anon_sym_let,
      anon_sym_var,
    STATE(69), 3,
      sym_declaration,
      sym_assignment,
      sym_control,
    ACTIONS(41), 4,
      anon_sym_return,
      anon_sym_throw,
      anon_sym_break,
      anon_sym_continue,
  [557] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_ident,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_expression,
    STATE(73), 1,
      sym_statement,
    ACTIONS(39), 2,
      anon_sym_let,
      anon_sym_var,
    STATE(69), 3,
      sym_declaration,
      sym_assignment,
      sym_control,
    ACTIONS(41), 4,
      anon_sym_return,
      anon_sym_throw,
      anon_sym_break,
      anon_sym_continue,
  [588] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_ident,
    ACTIONS(53), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_expression,
    STATE(53), 1,
      sym_statement,
    ACTIONS(39), 2,
      anon_sym_let,
      anon_sym_var,
    STATE(69), 3,
      sym_declaration,
      sym_assignment,
      sym_control,
    ACTIONS(41), 4,
      anon_sym_return,
      anon_sym_throw,
      anon_sym_break,
      anon_sym_continue,
  [619] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_ident,
    ACTIONS(57), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_expression,
    STATE(73), 1,
      sym_statement,
    ACTIONS(39), 2,
      anon_sym_let,
      anon_sym_var,
    STATE(69), 3,
      sym_declaration,
      sym_assignment,
      sym_control,
    ACTIONS(41), 4,
      anon_sym_return,
      anon_sym_throw,
      anon_sym_break,
      anon_sym_continue,
  [650] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_ident,
    STATE(5), 1,
      sym_expression,
    STATE(73), 1,
      sym_statement,
    ACTIONS(39), 2,
      anon_sym_let,
      anon_sym_var,
    STATE(69), 3,
      sym_declaration,
      sym_assignment,
      sym_control,
    ACTIONS(41), 4,
      anon_sym_return,
      anon_sym_throw,
      anon_sym_break,
      anon_sym_continue,
  [678] = 8,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_func,
    ACTIONS(61), 1,
      anon_sym_SEMI,
    ACTIONS(63), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      aux_sym_resource_repeat1,
    STATE(41), 1,
      sym_newline,
    ACTIONS(65), 2,
      anon_sym_LF,
      anon_sym_CR,
    STATE(83), 2,
      sym_func,
      aux_sym_resource_repeat2,
  [705] = 8,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_func,
    ACTIONS(67), 1,
      anon_sym_SEMI,
    ACTIONS(69), 1,
      anon_sym_RBRACE,
    STATE(24), 1,
      aux_sym_resource_repeat1,
    STATE(34), 1,
      sym_newline,
    ACTIONS(65), 2,
      anon_sym_LF,
      anon_sym_CR,
    STATE(66), 2,
      sym_func,
      aux_sym_resource_repeat2,
  [732] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    ACTIONS(71), 8,
      anon_sym_func,
      anon_sym_let,
      anon_sym_var,
      anon_sym_return,
      anon_sym_throw,
      anon_sym_break,
      anon_sym_continue,
      sym_ident,
  [749] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_func,
    ACTIONS(11), 1,
      anon_sym_record,
    ACTIONS(13), 1,
      anon_sym_resource,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    STATE(29), 2,
      sym_toplevel,
      aux_sym_source_file_repeat1,
    STATE(80), 3,
      sym_func,
      sym_record,
      sym_resource,
  [774] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_func,
    ACTIONS(11), 1,
      anon_sym_record,
    ACTIONS(13), 1,
      anon_sym_resource,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    STATE(30), 2,
      sym_toplevel,
      aux_sym_source_file_repeat1,
    STATE(80), 3,
      sym_func,
      sym_record,
      sym_resource,
  [799] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_func,
    ACTIONS(11), 1,
      anon_sym_record,
    ACTIONS(13), 1,
      anon_sym_resource,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    STATE(30), 2,
      sym_toplevel,
      aux_sym_source_file_repeat1,
    STATE(80), 3,
      sym_func,
      sym_record,
      sym_resource,
  [824] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 1,
      anon_sym_func,
    ACTIONS(84), 1,
      anon_sym_record,
    ACTIONS(87), 1,
      anon_sym_resource,
    STATE(30), 2,
      sym_toplevel,
      aux_sym_source_file_repeat1,
    STATE(80), 3,
      sym_func,
      sym_record,
      sym_resource,
  [849] = 6,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_SEMI,
    STATE(31), 1,
      aux_sym_resource_repeat1,
    STATE(106), 1,
      sym_newline,
    ACTIONS(90), 2,
      anon_sym_func,
      anon_sym_RBRACE,
    ACTIONS(95), 2,
      anon_sym_LF,
      anon_sym_CR,
  [870] = 2,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(98), 7,
      anon_sym_func,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LF,
      anon_sym_CR,
  [883] = 6,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_SEMI,
    ACTIONS(102), 1,
      anon_sym_RBRACE,
    STATE(17), 1,
      sym_newline,
    STATE(48), 1,
      aux_sym_func_repeat2,
    ACTIONS(65), 2,
      anon_sym_LF,
      anon_sym_CR,
  [903] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_func,
    ACTIONS(104), 1,
      sym_ident,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    STATE(56), 1,
      sym_field,
    STATE(83), 2,
      sym_func,
      aux_sym_resource_repeat2,
  [923] = 6,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_COMMA,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
    STATE(39), 1,
      aux_sym_record_repeat1,
    STATE(88), 1,
      sym_newline,
    ACTIONS(65), 2,
      anon_sym_LF,
      anon_sym_CR,
  [943] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_func,
    ACTIONS(104), 1,
      sym_ident,
    ACTIONS(112), 1,
      anon_sym_RBRACE,
    STATE(25), 1,
      sym_field,
    STATE(77), 2,
      sym_func,
      aux_sym_resource_repeat2,
  [963] = 4,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(114), 1,
      sym_ident,
    STATE(4), 1,
      sym_expression,
    ACTIONS(116), 4,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LF,
      anon_sym_CR,
  [979] = 6,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_SEMI,
    ACTIONS(120), 1,
      anon_sym_RBRACE,
    STATE(12), 1,
      sym_newline,
    STATE(42), 1,
      aux_sym_func_repeat2,
    ACTIONS(65), 2,
      anon_sym_LF,
      anon_sym_CR,
  [999] = 6,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(122), 1,
      anon_sym_COMMA,
    ACTIONS(125), 1,
      anon_sym_RBRACE,
    STATE(39), 1,
      aux_sym_record_repeat1,
    STATE(103), 1,
      sym_newline,
    ACTIONS(127), 2,
      anon_sym_LF,
      anon_sym_CR,
  [1019] = 4,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(132), 1,
      anon_sym_COLON,
    ACTIONS(134), 1,
      anon_sym_EQ,
    ACTIONS(130), 4,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LF,
      anon_sym_CR,
  [1035] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_func,
    ACTIONS(104), 1,
      sym_ident,
    ACTIONS(136), 1,
      anon_sym_RBRACE,
    STATE(56), 1,
      sym_field,
    STATE(72), 2,
      sym_func,
      aux_sym_resource_repeat2,
  [1055] = 6,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_SEMI,
    ACTIONS(140), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      sym_newline,
    STATE(45), 1,
      aux_sym_func_repeat2,
    ACTIONS(65), 2,
      anon_sym_LF,
      anon_sym_CR,
  [1075] = 6,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_SEMI,
    ACTIONS(140), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      sym_newline,
    STATE(47), 1,
      aux_sym_func_repeat2,
    ACTIONS(65), 2,
      anon_sym_LF,
      anon_sym_CR,
  [1095] = 6,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_SEMI,
    ACTIONS(144), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      sym_newline,
    STATE(49), 1,
      aux_sym_func_repeat2,
    ACTIONS(65), 2,
      anon_sym_LF,
      anon_sym_CR,
  [1115] = 6,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_SEMI,
    ACTIONS(149), 1,
      anon_sym_RBRACE,
    STATE(23), 1,
      sym_newline,
    STATE(45), 1,
      aux_sym_func_repeat2,
    ACTIONS(151), 2,
      anon_sym_LF,
      anon_sym_CR,
  [1135] = 6,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_COMMA,
    ACTIONS(156), 1,
      anon_sym_RBRACE,
    STATE(35), 1,
      aux_sym_record_repeat1,
    STATE(92), 1,
      sym_newline,
    ACTIONS(65), 2,
      anon_sym_LF,
      anon_sym_CR,
  [1155] = 6,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_SEMI,
    ACTIONS(144), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      sym_newline,
    STATE(45), 1,
      aux_sym_func_repeat2,
    ACTIONS(65), 2,
      anon_sym_LF,
      anon_sym_CR,
  [1175] = 6,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_SEMI,
    ACTIONS(160), 1,
      anon_sym_RBRACE,
    STATE(20), 1,
      sym_newline,
    STATE(45), 1,
      aux_sym_func_repeat2,
    ACTIONS(65), 2,
      anon_sym_LF,
      anon_sym_CR,
  [1195] = 6,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_SEMI,
    ACTIONS(164), 1,
      anon_sym_RBRACE,
    STATE(19), 1,
      sym_newline,
    STATE(45), 1,
      aux_sym_func_repeat2,
    ACTIONS(65), 2,
      anon_sym_LF,
      anon_sym_CR,
  [1215] = 6,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_SEMI,
    ACTIONS(102), 1,
      anon_sym_RBRACE,
    STATE(17), 1,
      sym_newline,
    STATE(45), 1,
      aux_sym_func_repeat2,
    ACTIONS(65), 2,
      anon_sym_LF,
      anon_sym_CR,
  [1235] = 6,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_SEMI,
    ACTIONS(164), 1,
      anon_sym_RBRACE,
    STATE(19), 1,
      sym_newline,
    STATE(50), 1,
      aux_sym_func_repeat2,
    ACTIONS(65), 2,
      anon_sym_LF,
      anon_sym_CR,
  [1255] = 6,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(166), 1,
      anon_sym_SEMI,
    ACTIONS(168), 1,
      anon_sym_RBRACE,
    STATE(22), 1,
      sym_newline,
    STATE(45), 1,
      aux_sym_func_repeat2,
    ACTIONS(65), 2,
      anon_sym_LF,
      anon_sym_CR,
  [1275] = 6,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_SEMI,
    ACTIONS(160), 1,
      anon_sym_RBRACE,
    STATE(20), 1,
      sym_newline,
    STATE(52), 1,
      aux_sym_func_repeat2,
    ACTIONS(65), 2,
      anon_sym_LF,
      anon_sym_CR,
  [1295] = 2,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(170), 6,
      anon_sym_func,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LF,
      anon_sym_CR,
  [1307] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 5,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_record,
      anon_sym_resource,
  [1318] = 2,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(90), 5,
      anon_sym_func,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LF,
      anon_sym_CR,
  [1329] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 5,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_record,
      anon_sym_resource,
  [1340] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 5,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_record,
      anon_sym_resource,
  [1351] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_EQ,
    ACTIONS(31), 4,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LF,
      anon_sym_CR,
  [1364] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 5,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_record,
      anon_sym_resource,
  [1375] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 5,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_record,
      anon_sym_resource,
  [1386] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 5,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_record,
      anon_sym_resource,
  [1397] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 5,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_record,
      anon_sym_resource,
  [1408] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 5,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_record,
      anon_sym_resource,
  [1419] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 5,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_record,
      anon_sym_resource,
  [1430] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_func,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    STATE(68), 2,
      sym_func,
      aux_sym_resource_repeat2,
  [1444] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 4,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_record,
      anon_sym_resource,
  [1454] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      anon_sym_func,
    ACTIONS(197), 1,
      anon_sym_RBRACE,
    STATE(68), 2,
      sym_func,
      aux_sym_resource_repeat2,
  [1468] = 2,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(27), 4,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LF,
      anon_sym_CR,
  [1478] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 4,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_record,
      anon_sym_resource,
  [1488] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 4,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_record,
      anon_sym_resource,
  [1498] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_func,
    ACTIONS(203), 1,
      anon_sym_RBRACE,
    STATE(68), 2,
      sym_func,
      aux_sym_resource_repeat2,
  [1512] = 2,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(149), 4,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LF,
      anon_sym_CR,
  [1522] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 4,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_record,
      anon_sym_resource,
  [1532] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 4,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_record,
      anon_sym_resource,
  [1542] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 4,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_record,
      anon_sym_resource,
  [1552] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_func,
    ACTIONS(211), 1,
      anon_sym_RBRACE,
    STATE(68), 2,
      sym_func,
      aux_sym_resource_repeat2,
  [1566] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 4,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_record,
      anon_sym_resource,
  [1576] = 2,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(125), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LF,
      anon_sym_CR,
  [1586] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 4,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_record,
      anon_sym_resource,
  [1596] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 4,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_record,
      anon_sym_resource,
  [1606] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 4,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_record,
      anon_sym_resource,
  [1616] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_func,
    ACTIONS(136), 1,
      anon_sym_RBRACE,
    STATE(68), 2,
      sym_func,
      aux_sym_resource_repeat2,
  [1630] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_COMMA,
    ACTIONS(223), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      aux_sym_func_repeat1,
  [1643] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      sym_ident,
    ACTIONS(227), 1,
      anon_sym_RPAREN,
    STATE(95), 1,
      sym_field,
  [1656] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_COMMA,
    ACTIONS(232), 1,
      anon_sym_RPAREN,
    STATE(86), 1,
      aux_sym_func_repeat1,
  [1669] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      sym_ident,
    ACTIONS(234), 1,
      anon_sym_RPAREN,
    STATE(95), 1,
      sym_field,
  [1682] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      sym_ident,
    ACTIONS(238), 1,
      anon_sym_RBRACE,
    STATE(79), 1,
      sym_field,
  [1695] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      sym_ident,
    ACTIONS(240), 1,
      anon_sym_RBRACE,
    STATE(46), 1,
      sym_field,
  [1708] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_RPAREN,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    STATE(86), 1,
      aux_sym_func_repeat1,
  [1721] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
  [1730] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      sym_ident,
    ACTIONS(246), 1,
      anon_sym_RBRACE,
    STATE(79), 1,
      sym_field,
  [1743] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      sym_ident,
    ACTIONS(248), 1,
      anon_sym_RPAREN,
    STATE(84), 1,
      sym_field,
  [1756] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_DASH_GT,
    ACTIONS(252), 1,
      anon_sym_LBRACE,
  [1766] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1774] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      sym_ident,
    STATE(121), 1,
      sym_type,
  [1784] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      sym_ident,
    STATE(115), 1,
      sym_type,
  [1794] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      sym_ident,
    STATE(6), 1,
      sym_expression,
  [1804] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_DASH_GT,
    ACTIONS(260), 1,
      anon_sym_LBRACE,
  [1814] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      sym_ident,
    STATE(95), 1,
      sym_field,
  [1824] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_DASH_GT,
    ACTIONS(264), 1,
      anon_sym_LBRACE,
  [1834] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      sym_ident,
    STATE(119), 1,
      sym_type,
  [1844] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      sym_ident,
    STATE(79), 1,
      sym_field,
  [1854] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      sym_ident,
    STATE(3), 1,
      sym_expression,
  [1864] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      sym_ident,
    STATE(107), 1,
      sym_type,
  [1874] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      sym_ident,
    STATE(56), 1,
      sym_field,
  [1884] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1892] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      sym_ident,
    STATE(59), 1,
      sym_type,
  [1902] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      sym_ident,
    STATE(7), 1,
      sym_expression,
  [1912] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      sym_ident,
    STATE(8), 1,
      sym_expression,
  [1922] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_DASH_GT,
    ACTIONS(272), 1,
      anon_sym_LBRACE,
  [1932] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      sym_ident,
    STATE(123), 1,
      sym_type,
  [1942] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      sym_ident,
    STATE(54), 1,
      sym_type,
  [1952] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      sym_ident,
  [1959] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      anon_sym_LBRACE,
  [1966] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      anon_sym_LPAREN,
  [1973] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      sym_ident,
  [1980] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      anon_sym_COLON,
  [1987] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_LBRACE,
  [1994] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      sym_ident,
  [2001] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_LBRACE,
  [2008] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      sym_ident,
  [2015] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_LBRACE,
  [2022] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 1,
      anon_sym_LBRACE,
  [2029] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      ts_builtin_sym_end,
  [2036] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 1,
      sym_ident,
  [2043] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      sym_ident,
  [2050] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 1,
      anon_sym_LBRACE,
  [2057] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 68,
  [SMALL_STATE(5)] = 99,
  [SMALL_STATE(6)] = 130,
  [SMALL_STATE(7)] = 161,
  [SMALL_STATE(8)] = 192,
  [SMALL_STATE(9)] = 221,
  [SMALL_STATE(10)] = 247,
  [SMALL_STATE(11)] = 278,
  [SMALL_STATE(12)] = 309,
  [SMALL_STATE(13)] = 340,
  [SMALL_STATE(14)] = 371,
  [SMALL_STATE(15)] = 402,
  [SMALL_STATE(16)] = 433,
  [SMALL_STATE(17)] = 464,
  [SMALL_STATE(18)] = 495,
  [SMALL_STATE(19)] = 526,
  [SMALL_STATE(20)] = 557,
  [SMALL_STATE(21)] = 588,
  [SMALL_STATE(22)] = 619,
  [SMALL_STATE(23)] = 650,
  [SMALL_STATE(24)] = 678,
  [SMALL_STATE(25)] = 705,
  [SMALL_STATE(26)] = 732,
  [SMALL_STATE(27)] = 749,
  [SMALL_STATE(28)] = 774,
  [SMALL_STATE(29)] = 799,
  [SMALL_STATE(30)] = 824,
  [SMALL_STATE(31)] = 849,
  [SMALL_STATE(32)] = 870,
  [SMALL_STATE(33)] = 883,
  [SMALL_STATE(34)] = 903,
  [SMALL_STATE(35)] = 923,
  [SMALL_STATE(36)] = 943,
  [SMALL_STATE(37)] = 963,
  [SMALL_STATE(38)] = 979,
  [SMALL_STATE(39)] = 999,
  [SMALL_STATE(40)] = 1019,
  [SMALL_STATE(41)] = 1035,
  [SMALL_STATE(42)] = 1055,
  [SMALL_STATE(43)] = 1075,
  [SMALL_STATE(44)] = 1095,
  [SMALL_STATE(45)] = 1115,
  [SMALL_STATE(46)] = 1135,
  [SMALL_STATE(47)] = 1155,
  [SMALL_STATE(48)] = 1175,
  [SMALL_STATE(49)] = 1195,
  [SMALL_STATE(50)] = 1215,
  [SMALL_STATE(51)] = 1235,
  [SMALL_STATE(52)] = 1255,
  [SMALL_STATE(53)] = 1275,
  [SMALL_STATE(54)] = 1295,
  [SMALL_STATE(55)] = 1307,
  [SMALL_STATE(56)] = 1318,
  [SMALL_STATE(57)] = 1329,
  [SMALL_STATE(58)] = 1340,
  [SMALL_STATE(59)] = 1351,
  [SMALL_STATE(60)] = 1364,
  [SMALL_STATE(61)] = 1375,
  [SMALL_STATE(62)] = 1386,
  [SMALL_STATE(63)] = 1397,
  [SMALL_STATE(64)] = 1408,
  [SMALL_STATE(65)] = 1419,
  [SMALL_STATE(66)] = 1430,
  [SMALL_STATE(67)] = 1444,
  [SMALL_STATE(68)] = 1454,
  [SMALL_STATE(69)] = 1468,
  [SMALL_STATE(70)] = 1478,
  [SMALL_STATE(71)] = 1488,
  [SMALL_STATE(72)] = 1498,
  [SMALL_STATE(73)] = 1512,
  [SMALL_STATE(74)] = 1522,
  [SMALL_STATE(75)] = 1532,
  [SMALL_STATE(76)] = 1542,
  [SMALL_STATE(77)] = 1552,
  [SMALL_STATE(78)] = 1566,
  [SMALL_STATE(79)] = 1576,
  [SMALL_STATE(80)] = 1586,
  [SMALL_STATE(81)] = 1596,
  [SMALL_STATE(82)] = 1606,
  [SMALL_STATE(83)] = 1616,
  [SMALL_STATE(84)] = 1630,
  [SMALL_STATE(85)] = 1643,
  [SMALL_STATE(86)] = 1656,
  [SMALL_STATE(87)] = 1669,
  [SMALL_STATE(88)] = 1682,
  [SMALL_STATE(89)] = 1695,
  [SMALL_STATE(90)] = 1708,
  [SMALL_STATE(91)] = 1721,
  [SMALL_STATE(92)] = 1730,
  [SMALL_STATE(93)] = 1743,
  [SMALL_STATE(94)] = 1756,
  [SMALL_STATE(95)] = 1766,
  [SMALL_STATE(96)] = 1774,
  [SMALL_STATE(97)] = 1784,
  [SMALL_STATE(98)] = 1794,
  [SMALL_STATE(99)] = 1804,
  [SMALL_STATE(100)] = 1814,
  [SMALL_STATE(101)] = 1824,
  [SMALL_STATE(102)] = 1834,
  [SMALL_STATE(103)] = 1844,
  [SMALL_STATE(104)] = 1854,
  [SMALL_STATE(105)] = 1864,
  [SMALL_STATE(106)] = 1874,
  [SMALL_STATE(107)] = 1884,
  [SMALL_STATE(108)] = 1892,
  [SMALL_STATE(109)] = 1902,
  [SMALL_STATE(110)] = 1912,
  [SMALL_STATE(111)] = 1922,
  [SMALL_STATE(112)] = 1932,
  [SMALL_STATE(113)] = 1942,
  [SMALL_STATE(114)] = 1952,
  [SMALL_STATE(115)] = 1959,
  [SMALL_STATE(116)] = 1966,
  [SMALL_STATE(117)] = 1973,
  [SMALL_STATE(118)] = 1980,
  [SMALL_STATE(119)] = 1987,
  [SMALL_STATE(120)] = 1994,
  [SMALL_STATE(121)] = 2001,
  [SMALL_STATE(122)] = 2008,
  [SMALL_STATE(123)] = 2015,
  [SMALL_STATE(124)] = 2022,
  [SMALL_STATE(125)] = 2029,
  [SMALL_STATE(126)] = 2036,
  [SMALL_STATE(127)] = 2043,
  [SMALL_STATE(128)] = 2050,
  [SMALL_STATE(129)] = 2057,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [15] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 6, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_control, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 4, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(127),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(126),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_newline, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_newline, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(126),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(122),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(114),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_resource_repeat1, 2, 0, 0),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_resource_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_resource_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(129),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_control, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [122] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0),
  [127] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [146] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_func_repeat2, 2, 0, 0), SHIFT_REPEAT(23),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_func_repeat2, 2, 0, 0),
  [151] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_func_repeat2, 2, 0, 0), SHIFT_REPEAT(26),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 3, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 6, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 7, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 8, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 9, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 11, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 10, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 12, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 13, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 14, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resource, 5, 0, 0),
  [194] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_resource_repeat2, 2, 0, 0), SHIFT_REPEAT(126),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_resource_repeat2, 2, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 7, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resource, 7, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resource, 8, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 4, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resource, 4, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 6, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_toplevel, 1, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resource, 6, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 5, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [229] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_func_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_func_repeat1, 2, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_operator, 1, 0, 0),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_operator, 1, 0, 0),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [292] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_wtf(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_ident,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
